name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for contributing to the Android x64 core project. Make sure to read the docs https://github.com/seanpm2001/Android-x64/Docs/ before making a contribution. This repository isn't for the actual operating system programming work, that set of projects is scattered across many repositories. Again, you can read more about this in the Android x64 Docs. Happy programming!"
        pr-message: "Thank you for contributing to the Android x64 core project. Make sure to read the docs https://github.com/seanpm2001/Android-x64/Docs/ before making a contribution. This repository isn't for the actual operating system programming work, that set of projects is scattered across many repositories. Again, you can read more about this in the Android x64 Docs. Happy programming!"
