/!Src/
/.github/
/.gitlab/
/Docs/
/Graphics/
/OldVersions/
/RepoData/
/.editorconfig
/.gitattributes
/.gitignore
/404.html
/404.jpeg
/404.md
/AUTHORS
/AUTHORS.md
/AUTOMATE2001.yaml
/AUTOMATE2001.yml
/Android-x64_REPOLIST.urll
/Android_Logo_HighDetail.png
/CITATION.cff
/CONTRIBUTING.md
/COPYINGL
/CREDITS
/CREDITS.wiki
/DRM-free_label.en.svg
/INITIAL_COMMIT.txt
/INSTALL
/INSTALL.rst
/K.desktop
/LICENSE-GPL.asm
/LICENSE-GPL.c
/LICENSE-GPL.h
/LICENSE-GPL.java
/LICENSE-GPL.txt
/LICENSE-GPL3.asm
/LICENSE-GPL3.c
/LICENSE-GPL3.h
/LICENSE-GPL3.java
/LICENSE-GPL3.txt
/LICENSE.asm
/LICENSE.c
/LICENSE.h
/LICENSE.java
/LICENSE.txt
/PROJECT_LANG_1.c
/PROJECT_LANG_1.h
/PROJECT_LANG_2.java
/PROJECT_LANG_3.asm
/README.md
/ROOTFILES.base
/SECURITY.md
/SponsorButton.png
/WacOS-Other.md
/_config.yml
/desktop.ini
/makefile.mk
/pull_request_template.md
